version: "3.8"

services:
  app:
    container_name: vuexy-nextjs-app
    build: .
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.zabano.com
      - NEXT_PUBLIC_DOMAIN_URL=https://zabano.com
      - NEXT_PUBLIC_CATALOG_CONTENT_URL=https://statics-zabano.s3.ir-thr-at1.arvanstorage.ir
      - NEXT_PUBLIC_CENTRIFUGE_BASE_URL=wss://eldorado.zabano.com

    restart: unless-stopped
